require "administrate/base_dashboard"

class UserDashboard < Administrate::BaseDashboard
  ATTRIBUTE_TYPES = {
    listings: Field::HasMany,
    id: Field::Number,
    provider: Field::String,
    uid: Field::String,
    encrypted_password: Field::String,
    reset_password_token: Field::String,
    reset_password_sent_at: Field::DateTime,
    allow_password_change: Field::Boolean,
    remember_created_at: Field::DateTime,
    sign_in_count: Field::Number,
    current_sign_in_at: Field::DateTime,
    last_sign_in_at: Field::DateTime,
    current_sign_in_ip: Field::String,
    last_sign_in_ip: Field::String,
    confirmation_token: Field::String,
    confirmed_at: Field::DateTime,
    confirmation_sent_at: Field::DateTime,
    unconfirmed_email: Field::String,
    name: Field::String,
    nickname: Field::String,
    image: Field::String,
    email: Field::String,
    tokens: Field::String.with_options(searchable: false),
    created_at: Field::DateTime,
    updated_at: Field::DateTime,
    avatar_file_name: Field::String,
    avatar_content_type: Field::String,
    avatar_file_size: Field::Number,
    avatar_updated_at: Field::DateTime,
    avatar_source: Field::String,
  }.freeze

  COLLECTION_ATTRIBUTES = [
    :id,
    :uid,
    :provider,
    :listings,
  ].freeze

  SHOW_PAGE_ATTRIBUTES = [
    :listings,
    :id,
    :provider,
    :uid,
    :encrypted_password,
    :reset_password_token,
    :reset_password_sent_at,
    :allow_password_change,
    :remember_created_at,
    :sign_in_count,
    :current_sign_in_at,
    :last_sign_in_at,
    :current_sign_in_ip,
    :last_sign_in_ip,
    :confirmation_token,
    :confirmed_at,
    :confirmation_sent_at,
    :unconfirmed_email,
    :name,
    :nickname,
    :image,
    :email,
    :tokens,
    :created_at,
    :updated_at,
    :avatar_file_name,
    :avatar_content_type,
    :avatar_file_size,
    :avatar_updated_at,
    :avatar_source,
  ].freeze

  FORM_ATTRIBUTES = [
    :listings,
    :provider,
    :uid,
    :encrypted_password,
    :reset_password_token,
    :reset_password_sent_at,
    :allow_password_change,
    :remember_created_at,
    :sign_in_count,
    :current_sign_in_at,
    :last_sign_in_at,
    :current_sign_in_ip,
    :last_sign_in_ip,
    :confirmation_token,
    :confirmed_at,
    :confirmation_sent_at,
    :unconfirmed_email,
    :name,
    :nickname,
    :image,
    :email,
    :tokens,
    :avatar_file_name,
    :avatar_content_type,
    :avatar_file_size,
    :avatar_updated_at,
    :avatar_source,
  ].freeze


  def display_resource(user)
    user.uid
  end
end
